uniwhales/component-library

- src/atoms/icons/generalIcons/filledStyle/HeartStandard.tsx
- src/atoms/icons/iconWrapper.tsx
- src/atoms/icons/types.ts
- src/index.ts
- src/molecules/tokenPriceCard/tokenPriceCard.stories.tsx
- src/molecules/tokenPriceCard/tokenPriceCard.tsx
- src/molecules/txTableList/txTableList.stories.tsx
- src/organisms/searchFilterSelect/searchFilterSelect.stories.tsx
- src/organisms/searchFilterSelect/searchFilterSelect.tsx
- src/organisms/searchFilterSelect/searchFilterSelectComponents/indicatorsContainer.tsx
this is for transaction dashboard, when user enters address we are going to set the `isDropdownDisabled` to true and show only the input with button without dropdown
> add flag to not show dropdown in search filter select

- src/atoms/tags/tag.stories.tsx
- src/atoms/tags/tag.styles.ts
- src/atoms/tags/types.ts
Fixing type issues for styled CustomTag and Tag component
> refactoring types and styled properties for tag

- src/atoms/inputs/input.tsx
- src/atoms/tags/tag.styles.ts
Fixes margin around tags and input being always disabled
> Post merge fixes

- src/atoms/uniwhalesLogo/uniwhalesLogo.stories.tsx
- src/atoms/uniwhalesLogo/uniwhalesLogo.tsx
https://uniwhales.atlassian.net/browse/FE-341
> add uniwhales logo

- src/atoms/footer/Footer.stories.tsx
- src/atoms/footer/Footer.styles.ts
- src/atoms/footer/Footer.tsx
- src/organisms/feedPageScollableContent/feedPageScrollableContent.stories.tsx
- src/organisms/feedPageScollableContent/feedPageScrollableContent.styles.ts
- src/organisms/feedPageScollableContent/feedPageScrollableContent.tsx
- src/organisms/feedPageScollableContent/types.ts
Adding basic scrollable component with footer and new updates section.
The new updates section is still awaiting design, so this is subject to change.
There is also a load more button needed, but again no design for this yet, so this may need adding in the future.
> Fe 337 - Centre Scrollable Component

- src/atoms/chips/chip.styles.ts
- src/atoms/chips/chip.tsx
- src/atoms/chips/types.ts
- src/molecules/cardDate/cardDate.stories.tsx
- src/molecules/cardDate/cardDate.tsx
- src/molecules/cardDate/styles.tsx
- src/molecules/cardDate/types.ts
https://uniwhales.atlassian.net/browse/FE-244
> add card datge

- src/atoms/texts/text.stories.tsx
- src/atoms/texts/text.styles.tsx
- src/atoms/texts/text.tsx
- src/atoms/texts/types.ts
https://uniwhales.atlassian.net/browse/FE-66
> add hyperlinks

- src/organisms/feedPageScrollableContent/feedPageScrollableContent.stories.tsx
- src/organisms/feedPageScrollableContent/feedPageScrollableContent.styles.ts
- src/organisms/feedPageScrollableContent/feedPageScrollableContent.tsx
- src/organisms/feedPageScrollableContent/types.ts
Adding functionality for new updates button and function for showing new updates to be passed into the scrollable component and it is now placed outside of the scrolling part, so it will always be visible.
In story I have showed basic implementation of how it will look with new updates (a few seconds after mount) and merging new updates into the feed.
> adding scroll button and styles with scroll to top behaviour

- src/atoms/inputs/select.stories.tsx
- src/atoms/inputs/select.tsx
- src/index.ts
- src/organisms/actionBar/types.ts
- src/organisms/announcementCard/AnnouncementCard.tsx
- src/organisms/announcementCard/styles.tsx
- src/organisms/announcementCard/types.ts
- src/organisms/contentCard/contentCard.stories.tsx
- src/organisms/contentCard/contentCard.tsx
- src/organisms/contentCard/styles.tsx
- src/organisms/contentCard/types.ts
- src/organisms/feedPageNavBar/feedPageNavBar.tsx
- src/organisms/feedPageNavBar/types.ts
Includes fixes for: 
https://uniwhales.atlassian.net/browse/FE-358
https://uniwhales.atlassian.net/browse/FE-328
> fix select types and tweak cards component

- src/organisms/actionBar/actionBar.stories.tsx
- src/organisms/actionBar/actionBar.styles.ts
- src/organisms/actionBar/actionBar.tsx
- src/organisms/actionBar/types.ts
Tx Type select fro action bar added with checkbox. I am just confirming with Michal whether we can use existing select styles or we need new ones.
> adding txtype checkbox select for action bar

- package.json
- src/atoms/chips/chip.styles.ts
- src/atoms/texts/text.stories.tsx
- src/atoms/texts/text.styles.tsx
- src/atoms/texts/text.tsx
- src/atoms/texts/textGenerator.ts
- src/atoms/texts/types.ts
- src/index.ts
- src/molecules/cardDate/cardDate.tsx
- src/molecules/cardDate/styles.tsx
- src/molecules/cardDate/types.ts
I updated card date to the latest design, 
https://www.figma.com/file/ZpdpHZRBooN4taSjRuKUQY/UniWhales-Main-V2-May-2022?node-id=6105%3A566862
1. I had to add new text size, i also noticed the line-height was off because it was the same for every text size so i adjusted it so that it makes sense to my eye so please have a look at the text inside storybook. 
2. Removed the type from the line heights/font sizes because the type will be derived from the object freeze. 
3. I also removed font sizes/font weights from the chip components since text should be defined always by text component
4. Exported layouts and breakpoints as i forgot to do it last time
> update card date to latest design

- package.json
- src/atoms/chips/chip.stories.tsx
- src/atoms/chips/chip.styles.ts
- src/atoms/chips/chip.tsx
- src/atoms/chips/filterChip.stories.tsx
- src/atoms/chips/filterChip.tsx
- src/atoms/chips/types.ts
- src/atoms/tags/tag.stories.tsx
- src/atoms/tags/tag.styles.ts
- src/atoms/tags/tag.tsx
- src/atoms/tags/types.ts
Contains updates to tags,chips and filter chips, i needed them to have different width than usual (which is fit-content).
I also centered text in tags,
> Fe 363 updates

- package.json
- src/atoms/texts/text.stories.tsx
- src/atoms/texts/text.tsx
- src/atoms/texts/textGenerator.ts
- src/atoms/texts/types.ts
> adding 10px font size

- package.json
- src/atoms/buttons/button.tsx
Round Tiny button reduced from 24px => 20px
> reducing round-tiny to 20px

- package-lock.json
- package.json
- src/index.ts
Adding identicon component to exports for use in feed page
> Identicon component

- src/organisms/actionBar/actionBar.tsx
Adding text child component for action bar
> fixing action bar

- package.json
- src/atoms/inputs/select.stories.tsx
- src/atoms/inputs/select.tsx
- src/organisms/actionBar/actionBar.stories.tsx
- src/organisms/actionBar/actionBar.styles.ts
- src/organisms/actionBar/actionBar.tsx
- src/organisms/actionBar/types.ts
Refining types for select with help of @ArinCantCode 
Finalising styling for react select with groups
> Action bar fix

- package.json
- src/atoms/inputs/input.stories.tsx
- src/atoms/inputs/input.tsx
Fixing icon color on hover and sizing issues
> input fixes

- package.json
- src/atoms/inputs/select.tsx
- src/organisms/actionBar/actionBar.stories.tsx
small tweaks to clear button and fixing types on action bar
> Select tweaks

- package.json
- src/atoms/modal/modal.stories.tsx
- src/atoms/modal/modal.tsx
- src/atoms/modal/modalModel.tsx
- src/atoms/modal/types.ts
Added an optional `noCloseIcon` prop to modal.
Added optional flag to existing `height` prop as TS was complaining, that no height prop was added.
@ArinCantCode let me know if that was intentional and I will revert
> Modal tweaks

- package.json
- src/organisms/navbar/navbar.tsx
Adding click outside functionality to navbar
> Navbar click outside

- package.json
- src/atoms/inputs/select.stories.tsx
- src/atoms/inputs/select.tsx
Fixing kebab case issue on select.
Adding optional `order` property for select options. Backend currently providing `order` field on some lists so we can control order of items in dropdown
> Shan fixes

- package.json
- src/atoms/buttons/button.tsx
- src/atoms/footer/Footer.tsx
- src/atoms/toggles/toggle__standart.tsx
- src/organisms/navbar/navbar.tsx
- src/theme.ts
- Adding disabled state for toggle
- Updating styles for disabled state on buttons
- Updating theme colours
> updating theme and disabled state for toggle and buttons

- src/index.ts
- src/molecules/popover/PopoverComponent.tsx
- src/molecules/popover/popoverComponent.stories.tsx
- src/molecules/popover/types.ts
- src/molecules/tooltip/TooltipComponent.tsx
Adding popover component for more dynamic use cases
> Tooltip fix

- package.json
- src/index.ts
- src/molecules/hoverCard/hoverCard.stories.tsx
- src/molecules/hoverCard/hoverCard.tsx
- src/molecules/hoverCard/types.ts
- src/molecules/popover/PopoverComponent.tsx
- src/molecules/popover/popoverComponent.stories.tsx
- src/molecules/tooltip/TooltipComponent.tsx
HoverCard and Popover components added
> Popover tweaks

- package.json
- src/atoms/radio/radio.stories.tsx
- src/atoms/radio/radio.styles.ts
- src/atoms/radio/radio.tsx
- src/atoms/radio/types.ts
- src/index.ts
- src/utils/getSize.ts
Adjusting checkbox styling to match new design and exporting radio button from comp lib
> Radio Button styling changes

- package.json
- src/atoms/inputs/select.tsx
- src/organisms/actionBar/actionBar.stories.tsx
- src/organisms/actionBar/actionBar.tsx
- src/organisms/actionBar/types.ts
Now that we are using url params on feed page, the out of the box clear indicator clears the select but does not clear the URL params.
So we now have `handleClearValue`
> Custom clear function select

- src/atoms/radio/radio.stories.tsx
- src/atoms/radio/radio.styles.ts
- src/atoms/radio/radio.tsx
Addition of defaultChecked value for radios buttons + small styling tweaks for disabled state
> default checked on radio button

- package.json
- src/atoms/radio/radio.tsx
> removing uncontrolled prop

- package.json
- src/atoms/inputs/select.stories.tsx
- src/atoms/inputs/select.tsx
Adding custom max menu height for select
---
- [] Firefox
- [] Safari 
---
> adding optional maxMenuHeight to select

- package.json
- src/organisms/navbar/styles.tsx
Removing pointer from cursor on left side children
---
https://uniwhales.atlassian.net/browse/FE-561?atlOrigin=eyJpIjoiOTdiMTQyMjgzY2Q3NDk4NWIyZDQ4Mjg1NTEyNjNmOTciLCJwIjoiaiJ9
- [] Safari 
- [] Storybook covers all new/pre-existing variations without need to change controls to test it
---
> Fe 561 changing the cursor after hovering over following

- package.json
- src/atoms/icons/generalIcons/filledStyle/NftSidebarStandard.tsx
- src/atoms/icons/iconWrapper.stories.tsx
- src/atoms/icons/index.ts
Adding missing icon
---
- [] Firefox
- [] Safari 
- [ X I have labeled the PR accordingly
---
> adding nft root icon

- package.json
- src/atoms/modal/modal.tsx
- src/atoms/modal/types.ts
optional modal icon
---
- [] Chrome/Brave
- [] Firefox
- [] Safari 
---
> optional modal icon

- package.json
- src/atoms/modal/modal.tsx
- src/atoms/modal/modalModel.tsx
- src/atoms/modal/styles.ts
- src/atoms/modal/types.ts
adding optional additional action to modal header
---
- [] Firefox
- [] Safari 
---
> Add additional action to modal header

- package.json
- src/atoms/modal/modal.tsx
- src/atoms/modal/modalModel.tsx
- src/atoms/modal/styles.ts
- src/atoms/modal/types.ts
Please include a summary of the changes and the related issue or feature
// e.g
Added additional input feature to be able to restrict input to:
- Only integers
- Only text
- Integers and floats
---
- [] Chrome/Brave
- [] Firefox
- [] Safari 
---
> Modal fixes

- package.json
- src/molecules/modals/modal.stories.tsx
- src/molecules/modals/modal.styles.ts
- src/molecules/modals/modal.tsx
- src/molecules/modals/types.ts
Restyling react portal modal version for customise page
---
- [] Firefox
- [] Safari 
---
> Portal modal tweaks

- package.json
- src/atoms/inputs/input.tsx
- src/atoms/modal/modal.tsx
- src/atoms/modal/styles.ts
- src/atoms/modal/types.ts
- src/molecules/modals/modal.stories.tsx
- src/molecules/modals/modal.styles.ts
- src/molecules/modals/modal.tsx
- src/molecules/modals/types.ts
- Made `inputState` optional, to stop having to pass `{ message: ' ', status: 'default' }`
- Made `headerText` optional inside modals, to avoid having to pass empty string
- Added useEffect to stop scrolling when modal is opening on react portal version to make it consistent with nice-modal version.
---
- [] Firefox
- [] Safari 
---
> Input and modal props tweaks

- package.json
- src/atoms/inputs/select.tsx
Fixes issue with icon sizing in select from this:
to this:
---
https://uniwhales.atlassian.net/browse/FE-631?atlOrigin=eyJpIjoiNGI4ZjQ5MzUwNTA0NDlmMDhkOGRmMWYzZjMyNGFjYWYiLCJwIjoiaiJ9
- [] Firefox
- [] Safari 
---
> Fe 631 fix icon size in dropdown on feed page

- package.json
- src/atoms/buttons/button.stories.tsx
- src/atoms/buttons/button.tsx
- src/atoms/icons/iconWrapper.tsx
Button adjustments in preparation for [FE-630](https://uniwhales.atlassian.net/browse/FE-630?atlOrigin=eyJpIjoiMzBmNWQ0ZDI0OTJjNGVhYjllOGEyMTMxOThmYWM2ZmQiLCJwIjoiaiJ9). Required changes are outlined in the [this google doc](https://docs.google.com/document/d/1LRQ54_-_afXZZjXFYNCNlohinv76KbKm/edit#heading=h.vft9veymjhlx)
---
- [] Firefox
- [] Safari 
---
> Fe 630 button tweaks

- package.json
- src/atoms/icons/feed/RevokeIcon.tsx
Please include a summary of the changes and the related issue or feature
// e.g
Added additional input feature to be able to restrict input to:
- Only integers
- Only text
- Integers and floats
---
- [] Firefox
- [] Safari 
---
> Gradient icons

- package.json
- src/atoms/inputs/checkbox.tsx
- src/atoms/inputs/select.tsx
Updating select checkbox to match new design
---
- [] Firefox
- [] Safari 
---
> Update select checkbox

- package.json
- src/atoms/icons/index.ts
> export blur icon

- package.json
- src/index.ts
missing exports for toast utils
> export toast utils

- src/atoms/inputs/textarea.tsx
https://user-images.githubusercontent.com/35912161/210975989-67700698-333a-4818-8d32-66d11c684f49.mp4
---
- [] Firefox
- [] Safari 
---
> remove z-index since its more than input dropdown

- src/atoms/inputs/textarea.tsx
add placeholder and maxLength for textarea component
---
- [] Firefox
- [] Safari 
---
> add mexLength, add placeholder

- package.json
- src/theme.ts
Add orange gradient vertical and horizontal
---
Needed for new identicon design  FE-813
---
> add orange gradient

- package.json
- src/atoms/identicon/Identicon.styles.ts
Update identicon to match new design 
https://www.figma.com/file/RriFGbMIzF5Bw87LJbkxpN/Cielo-Main-V1.4?node-id=11679%3A580843&t=0fGrbO0JY6Gke5Ip-0
---
https://uniwhales.atlassian.net/browse/FE-813?atlOrigin=eyJpIjoiNjZjZTcxZmM5ZDgxNDVmYzk2MTg1NDYyNDUyY2Q3YWUiLCJwIjoiaiJ9
---
> FE-813 update identicon design

- package.json
- src/atoms/buttons/button.tsx
Adding transparent border to tertiary button to stop the jumping when hovering over
---
https://uniwhales.atlassian.net/browse/FE-688?atlOrigin=eyJpIjoiOWY5OTc4YmI0MTFmNDFjM2JhYmQ0YTRhMmVkOTI1YzIiLCJwIjoiaiJ9
---
> FE-788 - the Unfollow\Follow list button is 'jumping' after hover

- package.json
- src/atoms/icons/index.ts
> add missing export

- package.json
- src/theme.ts
Adding new colours needed for pagination
> Theme addition

- package.json
- src/atoms/icons/chains/fullColorStyle/Canto.tsx
- src/atoms/icons/iconWrapper.stories.tsx
- src/atoms/icons/index.ts
adding canto icon
---
- [] Firefox
- [] Safari 
---
> add canto icon

- package.json
- src/organisms/dropdownSlider/dropdownSlider.stories.tsx
- src/organisms/dropdownSlider/minUsdSlider.tsx
- src/organisms/dropdownSlider/styles.ts
- src/organisms/dropdownSlider/types.ts
Adding position absolute to stop content being pushed around
Adding custom width and height prop for button
> Min usd tweaks

- package.json
- src/organisms/dropdownSlider/dropdownSlider.stories.tsx
- src/organisms/dropdownSlider/minUsdSlider.tsx
- src/organisms/dropdownSlider/styles.ts
- src/organisms/dropdownSlider/types.ts
adjusting min usd slider to be a controlled input, we can now handle value and setting value from props, this allows us to clear the value from an external source.
Also adjusted border colours
> Min usd external clear

- package.json
- src/atoms/inputs/input.tsx
- src/atoms/inputs/select.tsx
Fix up inputs and selects idle and hover states to make them consistent throughout
---
[FE-1019](https://uniwhales.atlassian.net/browse/FE-1019?atlOrigin=eyJpIjoiYTNmMGIxZDAyN2MyNDU4YTgzN2YxODBlNzI2MWVlY2IiLCJwIjoiaiJ9)
---
[FE-1019]: https://uniwhales.atlassian.net/browse/FE-1019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Input and select states

- package.json
- src/atoms/toggles/themeToggle.tsx
- Reduce width of theme toggle
- Switch layout of toggle and label
- Change bg colour of toggle 
---
Relates # (issue)
Needed for sidebar ticket
https://uniwhales.atlassian.net/browse/FE-1035?atlOrigin=eyJpIjoiMDUxNWVmNzEwMjlhNGY4Y2I4Zjg1MTY5YWU4YzlkZTIiLCJwIjoiaiJ9
---
> Update theme toggle

- package.json
- src/atoms/connectWalletButton/connectWalletButton.styles.ts
- src/atoms/connectWalletButton/connectWalletButton.tsx
- src/atoms/inputs/textarea.tsx
Remove transitional state from connect wallet button
---
---
> Connect wallet button updates

- src/atoms/connectWalletButton/connectWalletButton.styles.ts
> remove uneeded styles

- package.json
- src/atoms/inputs/input.tsx
- src/atoms/inputs/textarea.stories.tsx
- src/atoms/inputs/textarea.tsx
Bring textarea in line with inputs:
- add error state and error message
- add tabindex
- add required
- add consistent padding and styling
---
- [] Firefox
- [] Safari 
---
> Textarea updates

- package.json
- src/atoms/icons/chains/fullColorStyle/OpenseaProColor.tsx
- src/atoms/icons/iconWrapper.stories.tsx
- src/atoms/icons/index.ts
Add opensea pro icon
- [] Firefox
- [] Safari 
---
> add opensea pro icon

- package.json
- src/atoms/buttons/button.stories.tsx
- src/atoms/buttons/button.tsx
- src/atoms/buttons/types.ts
- src/atoms/filterChips/filterChip.styles.ts
- src/atoms/filterChips/filterChip.tsx
- src/atoms/inputs/input.stories.tsx
- src/atoms/inputs/input.tsx
- src/atoms/inputs/select.stories.tsx
- src/atoms/inputs/select.tsx
- src/atoms/inputs/textarea.stories.tsx
- src/atoms/inputs/textarea.tsx
- src/molecules/labeled/select/labeledSelect.tsx
- src/organisms/searchFilterSelect/searchFilterSelect.tsx
- Added maxLength and counter as you are typing into text area
- Added Poppins font family to text area
- Added `not-allowed` cursor for filter chip icons when disabled
- Updated label text on inputs/selects/textarea when disabled (you couldn't read them before)
- Added the new 1.5x border for all buttons/inputs/selects/textarea when disabled, to highlight them when on certain backgrounds
- unified background colour of selects and inputs when disabled
- updated zindex for select, to stop it sitting behind react loading skeleton
- Added optional `color` prop to button. For now it is applying on `special_small_subtle` and other small subtle variants as that is what is needed on customise page. If this works well we can consider using it on other variants. 
- Added a `showOnTop` prop to …
> Fe 1103 component library fixes

- package.json
- src/organisms/dropdownSlider/minUsdSlider.tsx
fix issue with slider
---
- [] Firefox
- [] Safari 
---
> Min usd slider fix

- package.json
- src/atoms/inputs/select.tsx
add break all to select options to maintain the width and styling of select options
---
---
> Fe 1120 we need to fix a component dropdown on the new configuration page long list name does not display correctly

- package.json
- src/atoms/inputs/input.tsx
- src/atoms/inputs/textarea.tsx
Maintaining error/input state for inputs and textarea even when component is focussed.
---
[FE-1147](https://uniwhales.atlassian.net/browse/FE-1147?atlOrigin=eyJpIjoiMjViNDgxY2M1YzViNDAzZDk3NjM4OWEzNGYzMWIzNGQiLCJwIjoiaiJ9)
---
[FE-1147]: https://uniwhales.atlassian.net/browse/FE-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fe 1147 the error in modals are disappear if click on the line

- package.json
- src/atoms/inputs/select.tsx
- src/molecules/labeled/select/labeledSelect.stories.tsx
Revert recent zindex change for seletcs
---
- [] Firefox
- [] Safari 
---
> Revert select zindex

- package.json
- src/theme.ts
Please include a summary of the changes and the related issue or feature
// e.g
Added additional input feature to be able to restrict input to:
- Only integers
- Only text
- Integers and floats
---
- [] Chrome/Brave
- [] Firefox
- [] Safari 
---
> FE-1279 - update theme values and version

- package.json
- src/atoms/chips/chip.styles.ts
- src/atoms/chips/chip.tsx
- src/atoms/chips/types.ts
- src/atoms/filterChips/filterChip.styles.ts
- src/atoms/filterChips/filterChip.tsx
- src/atoms/texts/text.stories.tsx
- src/atoms/texts/text.tsx
- src/atoms/texts/textGenerator.ts
- src/atoms/texts/types.ts
Add new 9pt font size
Update filter chips to have selected state and height to match figma
---
FE-1336
- [] Firefox
- [] Safari 
---
> New 9pt font
